version: '3'

services:
  vue-app:
    build:
      context: "./."
      dockerfile: "Dockerfile"
    ports:
      - 8081:8081
    volumes:
      - ./app:/src
    tty: true
    environment:
      - NODE_ENV=development
